baseURL = 'https://masanorihigashihara.github.io/Classic-Mathematics-Papers/'
languageCode = 'ja'
title = 'Classic Mathematics Papers'
theme = "hugo-book"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  # hugo-book theme configuration
  BookSection = 'papers'
  BookToC = true
  BookSearch = true
  
  # MathJax support
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.before]]
    name = "新着"
    weight = 1
  [[menu.before]]
    name = "数論報告 第1章"
    url = "/Classic-Mathematics-Papers/papers/hilbert/zahlbericht/slides/chapter1/"
    parent = "新着"
    weight = 1
  [[menu.before]]
    name = "ヘッケ 第1章§2"
    url = "/Classic-Mathematics-Papers/papers/hecke/algebraic-numbers/ch1-sec2/"
    parent = "新着"
    weight = 2
  [[menu.before]]
    name = "リー 変換群 第3巻"
    url = "/Classic-Mathematics-Papers/papers/lie/transformation-groups-3/"
    parent = "新着"
    weight = 3
